smhc: add is cleared functions and several unit test cases
rustsbi/allwinner-hal pull request #13
Opened 2024-10-08 14:57 UTC by Placebo27

Change `has_xxx_reset` to `is_xxx_reset_cleared` avoiding potential confusion that `DMA_RST`, `FIFO_RST` and `SOFT_RST` are write-1-set, auto-cleared by hardware.

For Global Control Register, add is DMA, FIFO, Software Reset signal cleared by hardware functions and related test cases.
For Command Register, add is command start cleared function and test cases.
 
Complete the structure read/write function unit tests for Uart Bus Gating Reset, SPI Clock and SPI Bus Gating Registers.

2024-10-08 15:04 UTC, luojia65 requested changes

2024-10-08 15:04 UTC, luojia65 commented on src/smhc.rs
> +    // Is command start cleared?
```suggestion
    /// Is command start cleared?
```

2024-10-08 15:37 UTC, Placebo27 commented on src/smhc.rs
> +    // Is command start cleared?
Thanks for the pointer.

2024-10-09 00:08 UTC, luojia65 approved these changes

2024-10-09 05:39 UTC, merged